name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "10 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This PR has not been updated in the last TBD days'
        stale-pr-message: 'This PR has not been updated in the last TBD days'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
        days-before-stale: 0
        days-before-close: -1
